<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/30 22:56:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm',
  'username' => 'diegox09',
  'password' => 'sputnik_86',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
