<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/04/01 11:05:14
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
