<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/03/30 22:58:16
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Admin',
        1 => 'Supervisor',
        2 => 'Manager',
      ),
    ),
  ),
  'listdefinekpi' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'savekpi' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'updatekpi' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'copykpi' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'deletedefinekpi' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'savereview' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
